"""
Django settings for escola project.

Generated by 'django-admin startproject' using Django 2.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z5@aw@85lz(_*#xpno9g&h8lj!be!i06013+cxvy-pz3b_h(1e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Aplicações
    'cursos',
    #Bibliotecas e Frameworks
    'django_filters',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'escola.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'escola.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#DRF
REST_FRAMEWORK = {
    #AUTENTICAÇÃO
    'DEFAULT_AUTHENTICATION_CLASSES':[
        #Autenticação via Sessão do Usuário no Sistema Django
        #'rest_framework.authentication.SessionAuthentication',
        #Autenticação via Token
        'rest_framework.authentication.TokenAuthentication',
    ],
    #PERMISSÕES 
    'DEFAULT_PERMISSION_CLASSES':[
        #PERMISSÕES GLOBAIS
        #Se ele é autenticado, pode fazer os métodos HTTP, se não, só leitura GET
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    #CONFIGURAÇÕES DE PAGINAÇÃO, SOMENTE UMA CONFIGURAÇÃO
    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
    #NUMERO DE ELEMENTOS POR PAGE, CONFIGURAÇÃO GLOBAL
    'PAGE_SIZE':2,
    #ADICIONANDO THROTTILING A API
    'DEFAULT_THROTTLE_CLASSES':[
        #Adicionando Throttling  a tipos de usuários
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    #NÚMERO DE REQUISIÇÕES PARA USUÁRIOS ANONIMOS E AUTENTICADOS POR MINUTO
    #O Django utiliza o Cache back que conta as requisições, mas na produção utilizar REDIS
    'DEFAULT_THROTTLE_RATES' :{
        'anon' : '5/minute', # Pode ser second, day, month, year
        'user' : '10/minute',
    }
}